# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qm8fCG7Akk_UcxI-hrgl8TBL9D3Jnxzm
"""

listofNumbers=[1, 2, 3, 4, 5, 6, 7, 8]
for number in listofNumbers:
  if (number % 2==0):
    print(number,"is even")
    else:
      print(number,"is odd")
print("all done")

import numpy as np
A= np.random.normal(25.0,5.0,10)
print(A)